### ISSUE TITLE
Trickster not retrive InfluxDB results from redis cache

### ISSUE THREAD

**Issue by cybergartar** [tricksterproxy/trickster#461]
Hi, I'm using Trickster for caching InfluxDB with Redis as a caching backend. I've found that sometimes when I make a request by refreshing panel in Grafana (with exactly the same time range and same query), instead of retrieving data from Redis, Trickster removes the existing cache, makes a request to upstream server and set the cache again like in below log.

```
2020-06-29T07:37:01.205532908Z time=2020-06-29T07:37:01.205238824Z app=trickster caller=cache/redis/redis.go:129 level=debug event="redis cache remove" key=influx-prod.dpc.1d4752772c4dc840104cf1dc70905d44
2020-06-29T07:37:06.65697508Z time=2020-06-29T07:37:06.656704137Z app=trickster caller=proxy/engines/access_logs.go:27 level=debug event="upstream request" uri="http://INFLUX_ADDRESS:8086/query?db=k6&epoch=ms&q=SELECT+max%28%22value%22%29+FROM+%2F%5Ehttp_req_duration%24%2F+WHERE+time+%3E%3D+1593199157445ms+and+time+%3C%3D+1593216497237ms+and+value+%3E+0+GROUP+BY+time%2815s%29+fill%280%29" userAgent=Grafana/6.7.2 code=200 size=21151 durationMS=5451 originType=influxdb handlerName=query method=GET originName=influxprod
2020-06-29T07:37:06.659840473Z time=2020-06-29T07:37:06.658842475Z app=trickster caller=proxy/engines/deltaproxycache.go:465 level=debug event="delta routine completed" cacheKey=influx-prod.dpc.1d4752772c4dc840104cf1dc70905d44 cacheStatus=purge reqStart=1593199155 reqEnd=1593216495
2020-06-29T07:37:06.659859095Z time=2020-06-29T07:37:06.659543556Z app=trickster caller=cache/redis/redis.go:100 level=debug event="redis cache store" key=influx-prod.dpc.1d4752772c4dc840104cf1dc70905d44
```

I'm not sure if this problem occurs by the query not matching the required pattern or not

```
SELECT max("value") FROM /^http_req_duration$/ WHERE time >= 1593199157445ms and time <= 1593216497237ms and value > 0 GROUP BY time(15s) fill(0)
```

but I think if it does not match the required pattern, it should not be cached in Redis and produces event above 🤔 Anyway, here is my Trickster configurations

```
[caches]
  [caches.default]
  cache_type = 'redis'
      [caches.default.index]
      reap_interval_secs = 3
      flush_interval_secs = 5
      max_size_bytes = 5368709120
      max_size_backoff_bytes = 16777216
      max_size_objects = 0
      max_size_backoff_objects = 1000

      [caches.default.redis]
      client_type = 'cluster'
      endpoints = ['MANY REDIS ENDPOINT AS CLUSTER']
      db = 0
      max_retries = 0
      min_retry_backoff_ms = 0
      max_retry_backoff_ms = 0
      dial_timeout_ms = 0
      read_timeout_ms = 0
      write_timeout_ms = 0
      pool_size = 0
      min_idle_conns = 0
      max_conn_age_ms = 0
      pool_timeout_ms = 0
      idle_timeout_ms = 0
      idle_check_frequency_ms = 0

    [negative_caches]
    [negative_caches.default]
    400 = 3
    404 = 3
    500 = 5
    502 = 5

[origins]
  [origins.influxprod]
  origin_type = 'influxdb'
  origin_url = 'http://INFLUX_ADDRESS:8086'
  cache_key_prefix = 'influx-prod'
  compressable_types = [ 'text/javascript', 'text/css', 'text/plain', 'text/xml', 'text/json', 'application/json', 'application/javascript', 'application/xml' ]
  backfill_tolerance_secs = 60
  timeseries_retention_factor = 4096
  timeseries_eviction_method = 'lru'
  max_object_size_bytes = 5242880
```

**Comment by jranson** [comment]
hi @cybergartar! thanks for using trickster, and for asking about this. i can see in the log section you provided that `cacheStatus=purge`. that is actually why the time series is being removed from the cache and refreshed. luckily it does not involve the query itself. this status means that a client (browser) included a `Cache-Control: no-cache` or `Cache-Control: no-store` http header with the incoming request for the data. caches like trickster generally respect that header by serving the object directly from the origin without caching it, while purging any existing copies. some web browsers will attach this header to a request when a user does a "deep refresh" instead of just a "basic refresh" in the browser via an additional key (e.g., `cmd/ctrl + shift + r` instead of just `cmd/ctrl + r` in google chrome). this ensures that any data anomalies perceived by the user can be can be reconciled for the user (and, if real, along that part of the delivery pipeline) with one additional request back to the origin. so the options are 1) accept that users will occasionally deep refresh and purge some cache entries, which is likely not too expensive on your backend; 2) directly ask users to avoid deep refreshing on your dashboard application, to minimize this condition; 3) configure a trickster [request rewriter](https://github.com/tricksterproxy/trickster/blob/master/docs/request_rewriters.md) to strip inbound `Cache-Control` headers to effectively disable client-based purging. 

option 3 is a lot easier than it sounds:
```toml
# add this section
[request_rewriters]
  [request_rewriters.remove-no-cache]
  instructions = [
    ['header', 'delete', 'Cache-Control', 'no-store'],
    ['header', 'delete', 'Cache-Control', 'no-cache'],
    ['header', 'delete', 'Pragma'] # http/1.0
  ]

[origins]
  [origins.influxprod]
  # reference the rewriter in your existing origin config like this:
  req_rewriter_name = 'remove-no-cache'
```

let me know if this helps you out!

**Comment by cybergartar** [comment]
The solution #3 helps solve the `cacheStatus=purge`, but I can still see there is a request to upstream server D:
```
2020-06-30T08:14:24.245660496Z time=2020-06-30T08:14:24.242258659Z app=trickster caller=cache/redis/redis.go:111 level=debug event="redis cache retrieve" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:25.911310966Z time=2020-06-30T08:14:25.910684477Z app=trickster caller=proxy/engines/access_logs.go:27 level=debug event="upstream request" userAgent=Grafana/6.7.2 code=200 originName=influxprod originType=influxdb handlerName=query method=GET uri="http://INFLUX_ADDR:8086/query?db=k6&epoch=ms&q=SELECT+max%28%22value%22%29+FROM+%2F%5Ehttp_req_duration%24%2F+WHERE+time+%3E%3D+1593199157445ms+and+time+%3C%3D+1593216497237ms+and+value+%3E+0+GROUP+BY+time%2810s%29+fill%280%29" size=33 durationMS=1665
2020-06-30T08:14:25.916205116Z time=2020-06-30T08:14:25.915754443Z app=trickster caller=proxy/engines/deltaproxycache.go:465 level=debug event="delta routine completed" cacheStatus=phit reqStart=1593199150 reqEnd=1593216490 extentsFetched=1593216440-1593216490 cacheKey=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:25.917682331Z time=2020-06-30T08:14:25.917518566Z app=trickster caller=cache/redis/redis.go:100 level=debug event="redis cache store" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:26.913580414Z time=2020-06-30T08:14:26.91345171Z app=trickster caller=cache/redis/redis.go:111 level=debug event="redis cache retrieve" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:30.218483839Z time=2020-06-30T08:14:30.218092812Z app=trickster caller=proxy/engines/access_logs.go:27 level=debug event="upstream request" originType=influxdb handlerName=query method=GET size=33 durationMS=3301 originName=influxprod userAgent=Grafana/6.7.2 code=200 uri="http://INFLUX_ADDR:8086/query?db=k6&epoch=ms&q=SELECT+max%28%22value%22%29+FROM+%2F%5Ehttp_req_duration%24%2F+WHERE+time+%3E%3D+1593199157445ms+and+time+%3C%3D+1593216497237ms+and+value+%3E+0+GROUP+BY+time%2810s%29+fill%280%29"
2020-06-30T08:14:30.223389784Z time=2020-06-30T08:14:30.222845225Z app=trickster caller=proxy/engines/deltaproxycache.go:465 level=debug event="delta routine completed" reqEnd=1593216490 extentsFetched=1593216440-1593216490 cacheKey=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8 cacheStatus=phit reqStart=1593199150
2020-06-30T08:14:30.224939223Z time=2020-06-30T08:14:30.224748362Z app=trickster caller=cache/redis/redis.go:100 level=debug event="redis cache store" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:32.681866611Z time=2020-06-30T08:14:32.679109045Z app=trickster caller=cache/redis/redis.go:111 level=debug event="redis cache retrieve" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:34.518413331Z time=2020-06-30T08:14:34.517731404Z app=trickster caller=proxy/engines/access_logs.go:27 level=debug event="upstream request" uri="http://INFLUX_ADDR:8086/query?db=k6&epoch=ms&q=SELECT+max%28%22value%22%29+FROM+%2F%5Ehttp_req_duration%24%2F+WHERE+time+%3E%3D+1593199157445ms+and+time+%3C%3D+1593216497237ms+and+value+%3E+0+GROUP+BY+time%2810s%29+fill%280%29" size=33 durationMS=1834 originName=influxprod originType=influxdb handlerName=query method=GET userAgent=Grafana/6.7.2 code=200
2020-06-30T08:14:34.524887325Z time=2020-06-30T08:14:34.524127739Z app=trickster caller=proxy/engines/deltaproxycache.go:465 level=debug event="delta routine completed" cacheKey=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8 cacheStatus=phit reqStart=1593199150 reqEnd=1593216490 extentsFetched=1593216440-1593216490
2020-06-30T08:14:34.526150019Z time=2020-06-30T08:14:34.52588286Z app=trickster caller=cache/redis/redis.go:100 level=debug event="redis cache store" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:38.892899782Z time=2020-06-30T08:14:38.891417353Z app=trickster caller=cache/redis/redis.go:111 level=debug event="redis cache retrieve" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
2020-06-30T08:14:40.557384913Z time=2020-06-30T08:14:40.557088908Z app=trickster caller=proxy/engines/access_logs.go:27 level=debug event="upstream request" uri="http://INFLUX_ADDR:8086/query?db=k6&epoch=ms&q=SELECT+max%28%22value%22%29+FROM+%2F%5Ehttp_req_duration%24%2F+WHERE+time+%3E%3D+1593199157445ms+and+time+%3C%3D+1593216497237ms+and+value+%3E+0+GROUP+BY+time%2810s%29+fill%280%29" userAgent=Grafana/6.7.2 code=200 durationMS=1661 originName=influxprod originType=influxdb method=GET handlerName=query size=33
2020-06-30T08:14:40.570805261Z time=2020-06-30T08:14:40.567334359Z app=trickster caller=proxy/engines/deltaproxycache.go:465 level=debug event="delta routine completed" cacheKey=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8 cacheStatus=phit reqStart=1593199150 reqEnd=1593216490 extentsFetched=1593216440-1593216490
2020-06-30T08:14:40.570826938Z time=2020-06-30T08:14:40.568965683Z app=trickster caller=cache/redis/redis.go:100 level=debug event="redis cache store" key=influx-prod.dpc.e2fb74c7d72958cfbd7519cc99101fa8
```

**Comment by cybergartar** [comment]
Also I've found panic while doing this query (which returns nothing when query in InfluxDB)

```
SELECT count("value") FROM "errors" WHERE time >= now() - 1h GROUP BY time(2s) fill(null)
```

```
2020-06-30T09:01:26.993742814Z 2020/06/30 09:01:26 http: panic serving 10.42.15.1:26863: runtime error: index out of range [0] with length 0
2020-06-30T09:01:26.993754483Z goroutine 60968 [running]:
2020-06-30T09:01:26.993757531Z net/http.(*conn).serve.func1(0xc0002f4820)
2020-06-30T09:01:26.993760061Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:1772 +0x139
2020-06-30T09:01:26.993762657Z panic(0xb58ac0, 0xc0010e82c0)
2020-06-30T09:01:26.993764865Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/panic.go:975 +0x3e3
2020-06-30T09:01:26.993767153Z github.com/tricksterproxy/trickster/pkg/proxy/origins/influxdb.(*SeriesEnvelope).Sort(0xc0004f5f80)
2020-06-30T09:01:26.99377013Z 	/home/runner/work/trickster/trickster/pkg/proxy/origins/influxdb/series.go:432 +0x3b0
2020-06-30T09:01:26.993772574Z github.com/tricksterproxy/trickster/pkg/proxy/origins/influxdb.(*SeriesEnvelope).Merge(0xc0004f5f80, 0x4325651a001, 0xc00038c6c0, 0x1, 0x1)
2020-06-30T09:01:26.99377531Z 	/home/runner/work/trickster/trickster/pkg/proxy/origins/influxdb/series.go:197 +0x3c7
2020-06-30T09:01:26.993777635Z github.com/tricksterproxy/trickster/pkg/proxy/engines.DeltaProxyCacheRequest(0xcc5fe0, 0xc0003b92f0, 0xc00013f900)
2020-06-30T09:01:26.993779957Z 	/home/runner/work/trickster/trickster/pkg/proxy/engines/deltaproxycache.go:380 +0x1b88
2020-06-30T09:01:26.99378221Z github.com/tricksterproxy/trickster/pkg/proxy/origins/influxdb.(*Client).QueryHandler(0xc0001585a0, 0xcc5fe0, 0xc0003b92f0, 0xc00013f900)
2020-06-30T09:01:26.993790941Z 	/home/runner/work/trickster/trickster/pkg/proxy/origins/influxdb/handler_query.go:46 +0x111
2020-06-30T09:01:26.993793577Z net/http.HandlerFunc.ServeHTTP(0xc0002c52c0, 0xcc5fe0, 0xc0003b92f0, 0xc00013f900)
2020-06-30T09:01:26.993795774Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2012 +0x44
2020-06-30T09:01:26.993797962Z github.com/tricksterproxy/trickster/pkg/util/middleware.WithResourcesContext.func1(0xcc5fe0, 0xc0003b92f0, 0xc00013f400)
2020-06-30T09:01:26.993800231Z 	/home/runner/work/trickster/trickster/pkg/util/middleware/config_context.go:43 +0x295
2020-06-30T09:01:26.99380251Z net/http.HandlerFunc.ServeHTTP(0xc00012f9e0, 0xcc5fe0, 0xc0003b92f0, 0xc00013f400)
2020-06-30T09:01:26.993805084Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2012 +0x44
2020-06-30T09:01:26.993838331Z github.com/tricksterproxy/trickster/pkg/proxy/request/rewriter.Rewrite.func1(0xcc5fe0, 0xc0003b92f0, 0xc00013f400)
2020-06-30T09:01:26.993841215Z 	/home/runner/work/trickster/trickster/pkg/proxy/request/rewriter/rewriter.go:71 +0x8e
2020-06-30T09:01:26.993843438Z net/http.HandlerFunc.ServeHTTP(0xc0002dec90, 0xcc5fe0, 0xc0003b92f0, 0xc00013f400)
2020-06-30T09:01:26.99384631Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2012 +0x44
2020-06-30T09:01:26.993848581Z github.com/tricksterproxy/trickster/pkg/util/middleware.Decorate.func1(0xcc5c60, 0xc000382320, 0xc00013f400)
2020-06-30T09:01:26.993851255Z 	/home/runner/work/trickster/trickster/pkg/util/middleware/metrics.go:38 +0x138
2020-06-30T09:01:26.993853546Z net/http.HandlerFunc.ServeHTTP(0xc0001314f0, 0xcc5c60, 0xc000382320, 0xc00013f400)
2020-06-30T09:01:26.993855685Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2012 +0x44
2020-06-30T09:01:26.993857856Z github.com/tricksterproxy/trickster/pkg/util/middleware.StripPathPrefix.func1(0xcc5c60, 0xc000382320, 0xc00013f400)
2020-06-30T09:01:26.993860147Z 	/home/runner/work/trickster/trickster/pkg/util/middleware/path.go:44 +0xb9
2020-06-30T09:01:26.993862353Z net/http.HandlerFunc.ServeHTTP(0xc0002decc0, 0xcc5c60, 0xc000382320, 0xc00013f400)
2020-06-30T09:01:26.993864474Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2012 +0x44
2020-06-30T09:01:26.993866917Z github.com/gorilla/mux.(*Router).ServeHTTP(0xc00029c540, 0xcc5c60, 0xc000382320, 0xc000b1ec00)
2020-06-30T09:01:26.993869156Z 	/home/runner/work/trickster/trickster/vendor/github.com/gorilla/mux/mux.go:210 +0xe2
2020-06-30T09:01:26.993871478Z github.com/tricksterproxy/trickster/pkg/proxy/handlers.(*SwitchHandler).ServeHTTP(0xc00018dfb0, 0xcc5c60, 0xc000382320, 0xc000b1ec00)
2020-06-30T09:01:26.993873742Z 	/home/runner/work/trickster/trickster/pkg/proxy/handlers/switch.go:43 +0x96
2020-06-30T09:01:26.993875898Z github.com/gorilla/handlers.CompressHandlerLevel.func1(0xcc64e0, 0xc000168540, 0xc000b1ec00)
2020-06-30T09:01:26.99387815Z 	/home/runner/work/trickster/trickster/vendor/github.com/gorilla/handlers/compress.go:148 +0x17b
2020-06-30T09:01:26.99388281Z net/http.HandlerFunc.ServeHTTP(0xc00030b180, 0xcc64e0, 0xc000168540, 0xc000b1ec00)
2020-06-30T09:01:26.993885146Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2012 +0x44
2020-06-30T09:01:26.993887352Z net/http.serverHandler.ServeHTTP(0xc000320000, 0xcc64e0, 0xc000168540, 0xc000b1ec00)
2020-06-30T09:01:26.993889514Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2807 +0xa3
2020-06-30T09:01:26.993891636Z net/http.(*conn).serve(0xc0002f4820, 0xcc8960, 0xc000188580)
2020-06-30T09:01:26.993893727Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:1895 +0x86c
2020-06-30T09:01:26.993895898Z created by net/http.(*Server).Serve
2020-06-30T09:01:26.993898259Z 	/opt/hostedtoolcache/go/1.14.3/x64/src/net/http/server.go:2933 +0x35c
```

**Comment by jranson** [comment]
@cybergartar  - We will take a look at this panic, that is definitely a bug! Thanks!

Regarding the upstream request, I see that those are no `cacheStatus=phit`, and the requested data points are for the 5 newest timestamps in the series. That suggests backfill tolerance, which you have set to 60s, is being applied, even though the time range for the query is not close to real time. We will double check to make sure this is what is happening and include that in the patch for the panic. Thanks again for the reports!

**Comment by jranson** [comment]
@cybergartar we have released v1.1.3 which should fix the both behaviors that you identified: the panic, and the backfill tolerance being applied to non-realtime queries. If you would not mind confirming those items are fixed, we'll close out this issue. Thanks again for using Trickster and reporting these issues.

**Comment by jranson** [comment]
closing due to no response (2wks). if you still have any problems in this issue, please reopen, thanks again for the report!
